# Generated by Django 3.2.9 on 2021-12-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('number', models.CharField(blank=True, max_length=128)),
                ('email', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Customera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('number', models.CharField(blank=True, max_length=128)),
                ('email', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('wdate', models.DateField(blank=True, null=True)),
                ('pamount', models.IntegerField(blank=True, null=True)),
                ('pinterest', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expensea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemanager.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoicea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('customera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemanager.customera')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ddate', models.DateField(blank=True, null=True)),
                ('rate', models.IntegerField(default=0)),
                ('invoicea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemanager.invoicea')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('money', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('ddate', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemanager.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAttachmenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoicea/')),
                ('displayname', models.CharField(max_length=128)),
                ('invoicea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemanager.invoicea')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoice/')),
                ('displayname', models.CharField(max_length=128)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemanager.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseAttachmenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='expensea/')),
                ('displayname', models.CharField(max_length=128)),
                ('expensea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemanager.expensea')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='expense/')),
                ('displayname', models.CharField(max_length=128)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemanager.expense')),
            ],
        ),
        migrations.AddField(
            model_name='expensea',
            name='invoicea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicemanager.invoicea'),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicemanager.invoice'),
        ),
    ]
